server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: simple-jdbc-demo
  datasource:
    url: "jdbc:mysql://localhost:3306/simple_db?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false"
    username: root
    password: bitnami
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      max-lifetime: 1800000
  datasource-slave1:
    url: "jdbc:mysql://localhost:3306/simple_db?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false"
    username: root
    password: bitnami
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 1800000
  datasource-slave2:
    url: "jdbc:mysql://localhost:3306/simple_db?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useLocalSessionState=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&elideSetAutoCommits=true&maintainTimeStats=false"
    username: root
    password: bitnami
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 1800000
  jackson:
# 3x   serialization:
#      write-dates-as-timestamps: true
    default-property-inclusion: NON_NULL
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
# 3.x   mongodb:
#      uri: mongodb://root:bitnami@localhost:27017/simple_db?authSource=admin
  mongodb:
    uri: mongodb://root:bitnami@localhost:27017/simple_db?authSource=admin
  elasticsearch:
    uris: http://localhost:9200
    socket-keep-alive: true

logging:
  level:
    root: info
    com.example.repository: debug

